### ISSUE TITLE
Eclipse does not start if the version 3.3.0 is installed when launching on JDK-11

### ISSUE THREAD

**Issue by tomsontom** [eclipse-efx/efxclipse-eclipse#42]

**Comment by nlisker** [comment]
Continuing https://bugs.eclipse.org/bugs/show_bug.cgi?id=539593

> What is the boot JDK? JDK-11?

As shown in the attached log file in the above, the JDK is 11.

**Comment by tomsontom** [comment]
there relevant fix is https://github.com/eclipse/efxclipse-rt/commit/48b44fdc1d030f5dc571a7a51af0b5e22ebf07d3

**Comment by tomsontom** [comment]
Just to clarify this one fixes the crash of eclipse, there's a 2nd problem shown in your sample. It looks lile javax.xml.bind can not be resolved when the Boot-JDK is Java-11. I logged #43 to track the fix for that

**Comment by tomsontom** [comment]
Changes are pushed and new build is running and should be done in ~15 minutes

**Comment by nlisker** [comment]
Thanks for the super-quick fix. So the problem was not related to the new Eclipse version, only the new java version? How long after the build is done will it be available in the update site?

**Comment by tomsontom** [comment]
http://download.eclipse.org/efxclipse/updates-nightly/site already contains the fixes we'll ship a patch release on Sunday 30th

**Comment by tomsontom** [comment]
people who push forward openjfx and eclipse get special treatment ;-)

**Comment by tomsontom** [comment]
Recover information:
* Start with none Java-11
* Update to the nightly build http://download.eclipse.org/efxclipse/updates-nightly/site
We'll try to ship a patch release ASAP

**Comment by nlisker** [comment]
Thanks! Version 3.3.0.201809272319 already solved the problem.

**Comment by tomsontom** [comment]
The new release 3.4.1 is available at http://download.eclipse.org/efxclipse/updates-released/3.4.1/site

**Comment by nadernader99** [comment]
I was experiencing the same problem with 3.3.0, which as of today is the version provided on the 2018-09 update site (http://download.eclipse.org/releases/2018-09).

The 3.4.1 version provided at http://download.eclipse.org/efxclipse/updates-released/3.4.1/site resolve my issue.  Thanks!

**Comment by tomsontom** [comment]
Yeah unfortunately it is not possible to update bits of those update-sites

**Comment by darmbrust** [comment]
adding the stack trace that happens when eclipse dies for search engines....

!ENTRY org.eclipse.osgi 4 0 2018-12-31 16:07:23.450
!MESSAGE Application error
!STACK 1
java.lang.NullPointerException
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.loadApplicationModel(E4Application.java:385)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:260)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:586)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)


It would seem that the main eclipse update site is still pushing a version that is completely broken.


If, like me, you broke your eclipse with that version, you need to go into the feature and plugins folder, and delete all of the files/folders with "fx" in them, then start eclipse, then, add a new update site pointing to http://download.eclipse.org/efxclipse/updates-nightly/site to get a version that works with jdk 11.

**Comment by tomsontom** [comment]
So what is the eclipse version you used? The 2018-12 update site should contain a fixed efxclipse version

**Comment by darmbrust** [comment]
I just installed 2018-12 on my linux box, and used the default update site to install it, and it broke eclipse.    When I looked at the version number, it was older than the version mentioned here where it was fixed.

Version: 2018-12 (4.10.0)
Build id: 20181214-0600

**Comment by darmbrust** [comment]
the default update site is showing me 3.3.0.201809010700

**Comment by tomsontom** [comment]
Grr so I messed up the contribution to the simrel repository. I think it is time to remove efxclipse from it

**Comment by Spyyder51** [comment]
This seems to be a thing still.
Ubuntu 16.04
Java JDK 11.0.02
Eclipse 2018-12 that I installed from fresh download 3 days ago
org.eclipse.platform=4.10.0.v20181206-0815
Install e(fx)clipse tonight through Help->Install New Software
Installed ok up to "do you want to restart?"
Clicked yes, haven't been able to open Eclipse since
And now looking for a "nice" way to fix it and/or remove e(fx)clipse to at least get Eclipse going again
I do PHP stuff normally, Java is a recent addition for "fun". So not overly familiar with the ins-n-outs of this.
UPDATE: Wiped and re-installed Eclipse and added the OpenFX SDK jars to get what I needed.

**Comment by tomsontom** [comment]
If you scroll up you‘ll there‘s a description how to fix without removing and reinstalling eclipse
