### ISSUE TITLE
Can't generate JavaFX Getters and Setters (Eclipse 2018-12 / 4.10)

### ISSUE THREAD

**Issue by judison** [eclipse-efx/efxclipse-eclipse#58]
It seems like deja-vu.

Eclipse 2018-12 (4.10), e(fx)clipse 3.4.1.20181003

```java
private StringProperty status = new SimpleStringProperty();
```

* Generate JavaFX Getters and Setters
* Clicking ok does nothing and generates this error: (from eclipse error log)
Unhandled event loop exception
```
java.lang.NoSuchMethodError: org.eclipse.jdt.internal.corext.codemanipulation.StubUtility2.getNodeToInsertBefore(Lorg/eclipse/jdt/core/dom/rewrite/ListRewrite;Lorg/eclipse/jdt/core/IJavaElement;)Lorg/eclipse/jdt/core/dom/ASTNode;
	at org.eclipse.fx.ide.jdt.ui.internal.handler.AddFXBeanGetterSetterHandler.generateAccessors(AddFXBeanGetterSetterHandler.java:365)
	at org.eclipse.fx.ide.jdt.ui.internal.handler.AddFXBeanGetterSetterHandler$GetterSetterDialog.okPressed(AddFXBeanGetterSetterHandler.java:272)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:469)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:622)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
...
```

**Comment by tomsontom** [comment]
yes this is because we call to internal APIs who change from time to time
