### ISSUE TITLE
Generate JavaFX Getters and Setters fails with exception

### ISSUE THREAD

**Issue by tomsontom** [eclipse-efx/efxclipse-eclipse#65]
moved from https://bugs.eclipse.org/bugs/show_bug.cgi?id=549072

**Comment by purringpigeon** [comment]
Hello,  is there a timeline when this might be fixed?  I have the latest plugin   e(fx)clipse - IDE	3.5.0.201907240300	org.eclipse.fx.ide.feature.feature.group	Eclipse.org from the Eclipse Market Place and this is still an issue.

This is my Eclipse version:

Version: 2019-03 (4.11)
Build id: I20190307-0500

Thank you.

**Comment by martinbluehweis** [comment]
> Hello, is there a timeline when this might be fixed? I have the latest plugin e(fx)clipse - IDE 3.5.0.201907240300 org.eclipse.fx.ide.feature.feature.group Eclipse.org from the Eclipse Market Place and this is still an issue.
> 
> This is my Eclipse version:
> 
> Version: 2019-03 (4.11)
> Build id: I20190307-0500
> 
> Thank you.

hi, this basically works for me (same version).
could you provide an example please, then I could have a look on it.

**Comment by purringpigeon** [comment]
Hello,

I have a JAVA POJO with a combination of Property fields, and several non Property fields.  I Right Click -> Source -> Generate JavaFX Getters/Setters.  The window pops up, I hit select all (it only shows the Property fields which is what used to happen).  I then hit OK.  Nothing happens.  I get the following exception.

!ENTRY org.eclipse.ui 4 0 2020-01-09 07:16:01.171
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.IllegalArgumentException
	at org.eclipse.jdt.core.dom.ASTParser.<init>(ASTParser.java:239)
	at org.eclipse.jdt.core.dom.ASTParser.newParser(ASTParser.java:134)
	at org.eclipse.jdt.internal.corext.refactoring.util.RefactoringASTParser.<init>(RefactoringASTParser.java:42)
	at org.eclipse.fx.ide.jdt.ui.internal.handler.AddFXBeanGetterSetterHandler$GetterSetterDialog.okPressed(AddFXBeanGetterSetterHandler.java:250)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:469)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:622)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.fx.ide.jdt.ui.internal.handler.AddFXBeanGetterSetterHandler.execute(AddFXBeanGetterSetterHandler.java:132)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)

[javafx-getter-setter-issue.zip](https://github.com/eclipse-efx/efxclipse-eclipse/files/4040781/javafx-getter-setter-issue.zip)

**Comment by tomsontom** [comment]
what java version do you target?

**Comment by purringpigeon** [comment]
My project targets Java 1.8.191

My Eclipse configuration is below:
*** Date: Thursday, January 9, 2020 at 8:22:55 AM Mountain Standard Time

*** Platform Details:

*** System properties:
applicationXMI=org.eclipse.ui.workbench/LegacyIDE.e4xmi
awt.toolkit=sun.awt.windows.WToolkit
ds.delayed.keepInstances=true
ds.delayed.keepInstances.default=true
eclipse.application=org.eclipse.ui.ide.workbench
eclipse.buildId=4.11.0.I20190307-0500
eclipse.commands=-os
win32
-ws
win32
-arch
x86_64
-showsplash
-launcher
C:\eclipse\eclipse.exe
-name
Eclipse
--launcher.library
C:\eclipse\\plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.1000.v20190125-2016\eclipse_1801.dll
-startup
C:\eclipse\\plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar
--launcher.appendVmargs
-vm
C:\Program Files\Java\jre1.8.0_201\bin\server\jvm.dll
eclipse.home.location=file:/C:/eclipse/
eclipse.launcher=C:\eclipse\eclipse.exe
eclipse.launcher.name=Eclipse
eclipse.p2.data.area=@config.dir/../p2/
eclipse.p2.profile=profile
eclipse.product=org.eclipse.sdk.ide
eclipse.startTime=1578522281003
eclipse.stateSaveDelayInterval=30000
eclipse.vm=C:\Program Files\Java\jre1.8.0_201\bin\server\jvm.dll
eclipse.vmargs=-Dosgi.requiredJavaVersion=1.8
-Dosgi.dataAreaRequiresExplicitInit=true
-Xms256m
-Xmx1024m
-Djava.class.path=C:\eclipse\\plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar
equinox.init.uuid=true
file.encoding=Cp1252
file.encoding.pkg=sun.io
file.separator=\
gosh.args=--nointeractive
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.awt.printerjob=sun.awt.windows.WPrinterJob
java.class.path=C:\eclipse\\plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar
java.class.version=52.0
java.endorsed.dirs=C:\Program Files\Java\jre1.8.0_201\lib\endorsed
java.ext.dirs=C:\Program Files\Java\jre1.8.0_201\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
java.home=C:\Program Files\Java\jre1.8.0_201
java.io.tmpdir=C:\Users\dfues\AppData\Local\Temp\
java.library.path=C:\eclipse;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:/Program Files/Java/jre1.8.0_201/bin/server;C:/Program Files/Java/jre1.8.0_201/bin;C:/Program Files/Java/jre1.8.0_201/lib/amd64;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\QFS\QF-Test\qftestpath;C:\app\client\dfues\product\12.1.0\client_1\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Java\jdk1.8.0_191\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\System32\OpenSSH\;C:\Users\dfues\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\dfues\AppData\Local\Programs\Python\Python37-32\;C:\Users\dfues\AppData\Local\Microsoft\WindowsApps;c:\gradle-2.12\bin;C:\Users\dfues\AppData\Local\Programs\Git\cmd;;C:\eclipse;;.
java.runtime.name=Java(TM) SE Runtime Environment
java.runtime.version=1.8.0_201-b09
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=1.8
java.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
java.version=1.8.0_201
java.vm.info=mixed mode
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.vendor=Oracle Corporation
java.vm.version=25.201-b09
jetty.git.hash=eb70b240169fcf1abbd86af36482d1c49826fa0b
line.separator=

**Comment by purringpigeon** [comment]
Did this information help?

**Comment by tomsontom** [comment]
not really we all run on Java-8 as well. What version does your project compiler settings point to?

**Comment by purringpigeon** [comment]
1.8.191

**Comment by purringpigeon** [comment]
Just for your reference i have uninstalled and reinstalled from Market Place the most current version with that results.

**Comment by tomsontom** [comment]
The build is not yet finished but what you need to do once the build is done is to point add http://download.eclipse.org/efxclipse/updates-nightly/site/ and update your current install with the bits contained in there.

I'll ping this issue once the build is done (Eclipse CI is quite slow) and the update-site is available

**Comment by purringpigeon** [comment]
Thank you

**Comment by tomsontom** [comment]
a new snapshot build is published please give it a spin

**Comment by purringpigeon** [comment]
I get the same behavior with the latest bits.  I installed the IDE option.

This is what is installed: Eclipse.org	JavaFX 2.0 Tooling	3.7.0.202001150800	org.eclipse.fx.ide.css.feature

!ENTRY org.eclipse.ui 4 0 2020-01-15 09:20:43.159
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.IllegalStateException: java.lang.NoSuchFieldException: SHARED_AST_LEVEL
	at org.eclipse.fx.ide.jdt.ui.internal.handler.AddFXBeanGetterSetterHandler$GetterSetterDialog.getAstLevelNotInlined(AddFXBeanGetterSetterHandler.java:253)
	at org.eclipse.fx.ide.jdt.ui.internal.handler.AddFXBeanGetterSetterHandler$GetterSetterDialog.okPressed(AddFXBeanGetterSetterHandler.java:261)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:469)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:622)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.fx.ide.jdt.ui.internal.handler.AddFXBeanGetterSetterHandler.execute(AddFXBeanGetterSetterHandler.java:133)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
Caused by: java.lang.NoSuchFieldException: SHARED_AST_LEVEL
	at java.lang.Class.getDeclaredField(Unknown Source)
	at org.eclipse.fx.ide.jdt.ui.internal.handler.AddFXBeanGetterSetterHandler$GetterSetterDialog.getAstLevelNotInlined(AddFXBeanGetterSetterHandler.java:250)
	... 56 more

**Comment by tomsontom** [comment]
Dumb mistaken on my behalf - build is triggered will take about an hour until available https://ci.eclipse.org/efxclipse/job/efxclipse_ide/1545/

**Comment by purringpigeon** [comment]
Thank you - that seems to have fixed it - just did a couple of quick tests, but looks good.  thank you.

**Comment by tomsontom** [comment]
thanks for testing and reporting back - highly appreciated
