### ISSUE TITLE
IllegalAccessError on each start

### ISSUE THREAD

**Issue by Samyssmile** [eclipse-efx/efxclipse-eclipse#67]
Hello, I just created an JavaFX RCP Sample Application. I use 

- Eclipse RCP 2019.06
- e(fx)clipse 3.6
- JDK 11
- javafx-sdk-11.0.2.
- Target Platform: EclipseFX - http://download.eclipse.org/efxclipse/runtime-nightly/site

A sample e4 application cant be started out of the box. So I need to add
--module-path "Z:\Development\javafx-sdk-11.0.2\lib" --add-modules javafx.controls,javafx.fxml,javafx.graphics
as VM Argument.

Now my Sample Application starts but on each start I see an error in the console
`Aug. 26, 2019 11:08:03 NACHM. org.eclipse.fx.ui.workbench.fx.DefaultJFXApp setProductApplicationName
SEVERE: Failed to set application name
java.lang.IllegalAccessError: class org.eclipse.fx.ui.workbench.fx.DefaultJFXApp (in unnamed module @0x15760615) cannot access class com.sun.glass.ui.Application (in module javafx.graphics) because module javafx.graphics does not export com.sun.glass.ui to unnamed module @0x15760615
	at org.eclipse.fx.ui.workbench.fx.DefaultJFXApp.setProductApplicationName(DefaultJFXApp.java:82)
	at org.eclipse.fx.ui.workbench.fx.DefaultJFXApp.<init>(DefaultJFXApp.java:54)
	at org.eclipse.fx.ui.workbench.fx.DefaultJFXApp.<init>(DefaultJFXApp.java:39)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:802)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

What is wrong?

**Comment by tomsontom** [comment]
The reason is that efxclipse needs to access internals to set the product name appropriately so you need to `-add-exports javafx.graphics/com.sun.javafx.application=ALL-UNNAMED, javafx.graphics/com.sun.glass.ui=ALL-UNNAMED`

**Comment by Samyssmile** [comment]
Thank you Tom,

for all who have same msg, this worked for me:

`--add-exports javafx.graphics/com.sun.javafx.application=ALL-UNNAMED
--add-exports javafx.graphics/com.sun.glass.ui=ALL-UNNAMED`

I really suggest to put this hint into the how to guide.

**Comment by tomsontom** [comment]
ups sorry yes no ',' - I hope we can generate an appropriate e4 application from the tooling in future - in the end our suggested way is to use our repackaged OpenJFX-Bundles because they contain the reexports already.

See https://github.com/eclipse-efx/efxclipse-eclipse/wiki/Eclipse4-application-on-OpenJFX-11
