### ISSUE TITLE
NPE at org.eclipse.fx.ide.pde.core.JavaFXClassPathExtender.findVMForEnv(JavaFXClassPathExtender.java:48)

### ISSUE THREAD

**Issue by zosrothko** [eclipse-efx/efxclipse-eclipse#88]
Hello

Got this NPE
```
java.lang.NullPointerException
	at org.eclipse.fx.ide.pde.core.JavaFXClassPathExtender.findVMForEnv(JavaFXClassPathExtender.java:48)
	at org.eclipse.fx.ide.pde.core.JavaFXClassPathExtender.getVM(JavaFXClassPathExtender.java:74)
	at org.eclipse.fx.ide.pde.core.JavaFXClassPathExtender.getInitialEntries(JavaFXClassPathExtender.java:180)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.computePluginEntries(RequiredPluginsClasspathContainer.java:99)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.getClasspathEntries(RequiredPluginsClasspathContainer.java:77)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3124)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3282)
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2359)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.getRootInfos(DeltaProcessingState.java:308)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.initializeRoots(DeltaProcessingState.java:256)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:730)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2316)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:804)
	at org.eclipse.jdt.core.JavaCore.setClasspathContainer(JavaCore.java:5803)
	at org.eclipse.jdt.internal.launching.JREContainerInitializer.initialize(JREContainerInitializer.java:72)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3184)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2120)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3619)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3118)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3282)
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2359)
	at org.eclipse.jdt.internal.core.JavaModelManager.determineIfOnClasspath(JavaModelManager.java:1169)
	at org.eclipse.jdt.internal.core.JavaModelManager.create(JavaModelManager.java:1063)
	at org.eclipse.jdt.internal.core.JavaModelManager.create(JavaModelManager.java:993)
	at org.eclipse.jdt.core.JavaCore.create(JavaCore.java:3498)
	at org.eclipse.jdt.internal.ui.ResourceAdapterFactory.getAdapter(ResourceAdapterFactory.java:47)
	at org.eclipse.core.internal.adapter.AdapterFactoryProxy.getAdapter(AdapterFactoryProxy.java:83)
	at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:295)
	at org.eclipse.core.runtime.PlatformObject.getAdapter(PlatformObject.java:68)
	at org.eclipse.jdt.ui.actions.FindAction.getJavaElements(FindAction.java:168)
	at org.eclipse.jdt.ui.actions.FindAction.canOperateOn(FindAction.java:111)
	at org.eclipse.jdt.ui.actions.FindAction.selectionChanged(FindAction.java:277)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchSelectionChanged(SelectionDispatchAction.java:259)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.selectionChanged(SelectionDispatchAction.java:254)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:155)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:152)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2179)
	at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1222)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1251)
	at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:240)
	at org.eclipse.jface.util.OpenStrategy.access$4(OpenStrategy.java:235)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
```

Session Data
```
eclipse.buildId=4.8.0.I20180611-0500
java.version=1.8.0_333
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -data file:/C:/MXW/EMU/develop/ -product org.eclipse.epp.package.jee.product
```

**Comment by tomsontom** [comment]
what version of e(fx)clipse is this?

**Comment by zosrothko** [comment]
e(fx)clipse - IDE	3.3.0.201805280700	org.eclipse.fx.ide.feature.feature.group	Eclipse.org

**Comment by tomsontom** [comment]
I guess there's a reason that you are on such old versions?

**Comment by zosrothko** [comment]
Yeap... At our company, we are stuck to Java 1.8 because of our customers. Thus the target Eclipse platform we can take should run with 1.8. We make the choice to use Photon.
